# include <iostream>
using namespace std;

int main() {
        cout << "invix";
        cout << "novqx";
        cout << "toepm";
        cout << "fxood";
        cout << "bdekh";
        cout << "kraui";
        cout << "yopbr";
        cout << "tpqqy";
        cout << "gidom";
        cout << "sbdat";
        cout << "anmxv";
        cout << "edrch";
        cout << "jvgoj";
        cout << "thvsh";
        cout << "cuoea";
        cout << "ifngm";
        cout << "ebdtx";
        cout << "uupmr";
        cout << "buinj";
        cout << "jakka";
        cout << "crxbu";
        cout << "gowiy";
        cout << "mkuvo";
        cout << "kqdsf";
        cout << "kogdl";
        cout << "ysubr";
        cout << "vfvej";
        cout << "abhwp";
        cout << "vyihg";
        cout << "shaxe";
        cout << "gksxu";
        cout << "leyei";
        cout << "jylel";
        cout << "civeb";
return 0;
}
